### ISSUE TITLE
Appellate links might not work in Big Cases Bot?

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#193]
@ERosendo can you take a look at a few tweets/toots from appellate cases and see if they share the problem this one has:

https://twitter.com/big_cases/status/1645870587812937728

It is sending a link to /docket/$case_id/$entry_id/$slug, but I feel like maybe that doesn't work for appellate?

Can you check, please? If all our appellate links are broken, that's a pretty big priority.

**Comment by ERosendo** [comment]
Sure! I'll take a look!

**Comment by mlissner** [comment]
That's interesting. Let's shift this to @albertisfu's backlog then. Maybe he has an idea why this could be. Any thoughts, Alberto?

**Comment by albertisfu** [comment]
Yeah, I found the problem.

The webhook was triggered when we got new entries from an appellate docket upload:
![Screenshot 2023-04-11 at 15 43 13](https://user-images.githubusercontent.com/486004/231294675-04c4a7b5-56b8-4d9b-8e86-a275e4de6f3e.png)

Then we got the attachment page for 52.

The problem is that appellate entries can have only a main RD or only attachments with no main RD, so when we get the entry we don't know if that entry has attachments until we get the attachment page.

If we get the attachment page for an entry then we convert the main document to an attachment as described here:
https://github.com/freelawproject/courtlistener/blob/main/cl/recap/mergers.py#L734

So that's why the main document is no longer accessible as it has been converted into an attachment.  I think this might be solved by doing a redirect from the "main document" If an attachment is now available we could do a redirect to the attachment.

Let me know what you think.

**Comment by mlissner** [comment]
Ah yes. I knew there was *something* weird about attachments, but I couldn't remember what. 

I agree, it seems like the simplest thing to do is to redirect this kind of thing to attachment 1. That should actually be a good one for @ERosendo, even though he's still pretty new to CL. Back to you, Eduardo, and Alberto, I'll leave you to your many other hot irons you've got in the fire.
